spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.145.128:3306/gulimall_pms
#    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
#      serverAddr: 127.0.0.1:8848
      # 以下配置项必须填写
#      username: nacos
#      password: nacos

      discovery:
        server-addr: 127.0.0.1:8848
#    alicloud:
#      access-Key: ${OSS_ACCESS_KEY_ID}
#      secret-key: ${OSS_ACCESS_KEY_SECRET}
#      oss:
#        endpoint: "oss-cn-beijing.aliyuncs.com"


#  application:
#    name: gulimall-product

  config:
    import:
      - nacos:nacos-config-example.properties?refreshEnabled=true&group=DEFAULT_GROUP




#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: 1
#      logic-not-delete-value: 0


server:
  port: 10000



